# ----- This file uses Faker to generate fake data to populate the e-commerce.db database, entirely generated by ChatGPT ----- #

import csv
import uuid
import lorem
import random

from faker import Faker
from datetime import datetime, timedelta

# Creating an instance of Faker() and setting seeds for replicability
random.seed(1)
fake = Faker()
fake.seed_instance(1)

# To generate random future dates (e.g. for delivery dates)
def random_future_date():
    return fake.date_between(start_date="today", end_date="+5w")

# To generate random past dates (e.g. for order dates)
def random_past_date():
    return fake.date_between(start_date="-1y", end_date="today")

# Categories and Product_Names (generated by ChatGPT)
product_subtypes = {
    'Toys and Games': ['Board Game', 'Action Figure', 'Educational Toy', 'Outdoor Play Set', 'Puzzle'],
    'Furniture': ['Sofa', 'Office Chair', 'Dining Table', 'Bed', 'Bookcase'],
    'Electronics': ['Smartphone', 'Laptop', 'Headphone', 'Smartwatch', 'Drone'],
    'Clothing and Apparel': ['T-Shirt', 'Jean', 'Jacket', 'Shoe', 'Accessory'],
    'Health and Beauty': ['Skincare Product', 'Hair Care', 'Makeup', 'Fragrance', 'Supplement'],
    'Books and Stationery': ['Novel', 'Academic Textbook', 'Notebook', 'Pen', 'Planner'],
    'Pet Supplies': ['Dog Food', 'Cat Litter', 'Pet Toy', 'Fish Tank', 'Pet Bed'],
    'Jewelry and Watches': ['Necklace', 'Ring', 'Bracelet', 'Earring', 'Wristwatch'],
    'Grocery and Gourmet Food': ['Organic Food', 'Snack', 'Beverage', 'Spice', 'Bakery Item'],
    'Baby Products': ['Diaper', 'Baby Bottle', 'Stroller', 'Baby Clothing', 'Crib']
}

# Generating a customer record
def generate_customer(customer_id):
    return {
        'Customer_ID': customer_id,
        'Email_Address': fake.email(),
        'Date_of_Birth': fake.date_of_birth(minimum_age=18).strftime('%Y-%m-%d'),
        'Building_NameNumber': fake.building_number() if random.choice([True, False]) else None,
        'Street': fake.street_name(),
        'City': fake.city(),
        'Country': fake.country(),
        'Postcode': fake.zipcode(),
        'Phone_Number': fake.phone_number(),
        'Password': fake.password(),
        'Name': fake.name()
    }

# Function to generate a product record
def generate_product(product_number):
    stock_quantity = stock_quantity = random.choices([0, random.randint(1, 200)], weights=[0.3, 0.7])[0]
    product_category = random.choice(list(product_subtypes.keys()))
    product_name = random.choice(product_subtypes[product_category])
    return {
        'Product_Number': product_number,
        'Product_Name': product_name,
        'Description': lorem.sentence(),
        'Brand': fake.company(),
        'Colour': fake.color_name(),
        'Depth': random.randint(1, 150),
        'Width': random.randint(1, 150),
        'Height': random.randint(1, 150),
        'Weight': round(random.uniform(0.5, 100.0), 2), # Generate a random weight between 0.5 and 100 kg
        'Price': float(f"{random.choice(range(10, 500, 5))}.00"),
        'Warranty': 2, # two year warranty on all products
        'Category': product_category,
        'Stock_Quantity': stock_quantity,
        'Is_Available': 'Y' if stock_quantity > 0 else 'N'
    }

# Function to generate credit_debit payment method
def generate_credit_debit(serial_card_number, customer):
    return {
        'Name': f"{customer['Name']}",
        'Verification_Code': fake.credit_card_number(),
        'Is_Default': random.choice(['Y', 'N']),
        'SerialCard_Number': serial_card_number,
    }

    # Function to generate voucher_giftcard payment method
def generate_voucher_giftcard(serial_card_number):
    total_amount = random.choice([20, 30, 40, 50, 100, 200])
    return {
        'Total_Amount': total_amount,
        'Current_Balance': random.randint(0, total_amount),
        'SerialCard_Number': serial_card_number,
    }

def generate_payment_method(customer_id):
    if random.random() > 0.2:  # 80% chance to generate a payment method
        serial_card_number = int(uuid.uuid4().hex[:12], 16)
        payment_method_type = random.choice(['credit_debit', 'voucher_giftcard'])  # Randomly choose type
        if payment_method_type == 'credit_debit':
            customer = generate_customer(customer_id)  # Generate customer for credit/debit card
            payment_method = generate_credit_debit(serial_card_number, customer)  # Generate credit/debit card details
        else:
            payment_method = generate_voucher_giftcard(serial_card_number)  # Generate voucher/giftcard details

        # Add common fields to the payment method record
        payment_method['SerialCard_Number'] = serial_card_number
        payment_method['Customer_ID'] = customer_id
        payment_method['Expiry_Date'] = random_future_date().strftime('%Y-%m-%d')
        return payment_method
    else:
        return None  # 20% chance the customer has no payment method

def generate_orders_and_ordered_products(products, customer_id):
    order_number = random.randint(10000, 99999) 
    
    def generate_ordered_product(order_number):
        selected_product = random.choice(products)
        product_number = selected_product['Product_Number']
        price = selected_product['Price']        
        num_ordered = random.randint(1, 100)
        return {
            'Product_Number': product_number,
            'Num_Ordered': num_ordered,
            'Product_Subtotal': round(price * num_ordered, 2),
            'Order_Number': order_number
        }

    def generate_order(order_number, customer_id, ordered_products):
        deduction_promotion = (random.choice(range(5, 101, 5)) / 100) if random.random() >= 0.9 else 0
        total = sum(item['Product_Subtotal'] for item in ordered_products if item['Order_Number'] == order_number)
        return {
            'Order_Number': order_number,
            'Date': random_past_date(),
            'Deduction_Promotion': deduction_promotion,
            'Total': round(total, 2),
            'Grand_Total': round(total * (1 - deduction_promotion), 2),
            'Customer_ID': customer_id
        }
    
    num_ordered_products = random.randint(1, 5)  # The function will select 3 unique products for that order.
    ordered_products = [generate_ordered_product(order_number) for _ in range(num_ordered_products)]
    
    order = generate_order(order_number, customer_id, ordered_products)
    return order, ordered_products

# Function to generate delivery
def generate_delivery(order_number, order_date, customer_id):
    customer = generate_customer(customer_id)
    date_of_delivery = order_date + timedelta(days=10)
    return {
        'Tracking_Number': fake.uuid4(),
        'Date_of_Delivery': date_of_delivery,
        'Status': random.choice(['delivered', 'postponed', 'cancelled', 'pending']),
        'Delivery_Address': f"{customer['Building_NameNumber']}, {customer['Street']}, {customer['City']}, {customer['Country']}, {customer['Postcode']}".strip(', '),
        'Order_Number': order_number
    }

# Function to generate a return
def generate_return(order_number, date_of_delivery, orders, deliveries):
    # only deliveries that are confirmed can be returned
    order = next((order for order in orders if order['Order_Number'] == order_number), None)
    confirmed_deliveries = [delivery for delivery in deliveries if delivery['Status'] == 'confirmed']
    delivery = next((delivery for delivery in confirmed_deliveries if delivery['Order_Number'] == order_number), None)
    # a customer can start a return within 30 days
    start_date = date_of_delivery
    return {
        'Ticket_Number': fake.uuid4(),
        'Order_Number': order_number,
        'Start_Date': start_date,
        'Due_Date': start_date + timedelta(days=30), # the return should arrive within 30 days
        'Refund_Total': order['Total'],
        'Status': random.choice(['completed', 'cancelled', 'denied', 'pending'])
    }

# Function to generate basket data
def generate_basket(customer_id, basket_id):
    return {
        'Basket_ID': "B" + str(basket_id),
        'Customer_ID': customer_id
    }

# Function to generate added_to data
def generate_added_to(basket_id, product_number):
    return {
        'Basket_ID': basket_id,
        'Product_Number': product_number,
        'Desired_Quantity': random.randint(1, 100)
    }

# Generate Data for each table
def generate_data():
    customers = [generate_customer(i) for i in range(1, 51)]
    products = [generate_product(i) for i in range(1, 100)]

    # First, generate all payment methods
    payment_methods = [generate_payment_method(i) for i in range(1, 51)]

    # Separate credit_debit and voucher_giftcard payment methods
    credit_debits = [
        {
            'SerialCard_Number': pm['SerialCard_Number'],
            'Name': pm['Name'],
            'Verification_Code': pm['Verification_Code'],
            'Is_Default': pm['Is_Default']
        }
        for pm in payment_methods if pm and 'Name' in pm  # Only include valid credit_debit methods
    ]

    voucher_giftcards = [
        {
            'SerialCard_Number': pm['SerialCard_Number'],
            'Total_Amount': pm['Total_Amount'],
            'Current_Balance': pm['Current_Balance']
        }
        for pm in payment_methods if pm and 'Total_Amount' in pm  # Only include valid voucher_giftcard methods
    ]

    payment_method_data = [
        {
            'SerialCard_Number': pm['SerialCard_Number'],
            'Customer_ID': pm['Customer_ID'],
            'Expiry_Date': pm['Expiry_Date']
        }
        for pm in payment_methods if pm is not None  # Ensure that the payment method exists
    ]

    # Orders and Ordered Products
    orders = []
    ordered_products = []
    for _ in range(1, 46):        
        customer_id = random.choice(customers)['Customer_ID'] # select a random customer_id from existing customers
        # generate the order and ordered products for this customer
        generated_order, generated_ordered_products = generate_orders_and_ordered_products(products, customer_id)
        
        # Add ordered products and the order to their lists
        ordered_products.extend(generated_ordered_products)
        orders.append(generated_order)

    deliveries = [
    generate_delivery(order['Order_Number'], order['Date'], order['Customer_ID'])
    for order in orders
    ]
    # Generate returns based on individual deliveries
    returns = [
        generate_return(order['Order_Number'], order['Date'], orders, deliveries)
        for order in orders[:5]  # Adjust the number of returns if needed
    ]

    baskets = [generate_basket(customer['Customer_ID'], i + 1) for i, customer in enumerate(customers)]
    basket_ids = [basket['Basket_ID'] for basket in baskets]

    # Generate 10 entries for 15 basket IDs and 4 entries for 10 basket IDs
    basket_ids_10 = random.sample(basket_ids, 15)
    basket_ids_4 = random.sample(list(set(basket_ids) - set(basket_ids_10)), 10)

    # Generate added_to entries while ensuring uniqueness of (Basket_ID, Product_Number)
    added_to = [
        generate_added_to(basket_id, product_number)
        for basket_id in basket_ids_10 + basket_ids_4
        for product_number in random.sample(range(1, 26), 10 if basket_id in basket_ids_10 else 4)
    ]

    # Write to CSV files
    def write_csv(file_name, data, fieldnames):
        with open(file_name, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.DictWriter(file, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(data)

    # Define fieldnames and write each table to its CSV
    write_csv('customers.csv', customers, ['Customer_ID', 'Email_Address', 'Date_of_Birth', 'Building_NameNumber', 'Street', 'City', 'Country', 'Postcode', 'Phone_Number', 'Password', 'Name'])
    write_csv('products.csv', products, ['Product_Number', 'Product_Name', 'Description', 'Brand', 'Colour', 'Depth', 'Width', 'Height', 'Weight', 'Price', 'Warranty', 'Category', 'Stock_Quantity', 'Is_Available'])
    write_csv('payment_methods.csv', payment_method_data, ['SerialCard_Number', 'Expiry_Date','Customer_ID',])
    write_csv('credit_debit.csv', credit_debits, ['Name', 'Verification_Code', 'Is_Default', 'SerialCard_Number'])
    write_csv('voucher_giftcard.csv', voucher_giftcards, ['Total_Amount', 'Current_Balance', 'SerialCard_Number'])
    write_csv('orders.csv', orders, ['Order_Number','Date', 'Deduction_Promotion', 'Total', 'Grand_Total','Customer_ID'])
    write_csv('ordered_products.csv', ordered_products, ['Product_Number', 'Product_Subtotal', 'Num_Ordered', 'Order_Number'])
    write_csv('deliveries.csv', deliveries, ['Tracking_Number', 'Date_of_Delivery', 'Status', 'Delivery_Address', 'Order_Number'])
    write_csv('returns.csv', returns, ['Ticket_Number', 'Order_Number', 'Start_Date', 'Due_Date', 'Refund_Total', 'Status'])
    write_csv('baskets.csv', baskets, ['Basket_ID', 'Customer_ID'])
    write_csv('added_to.csv', added_to, ['Desired_Quantity', 'Product_Number', 'Basket_ID',])


# Call the generate_data function to generate and save the data
generate_data()


